version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cloud-backend
hooks:
  BeforeInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user